-- Infinity Home — bootstrap schema for a NEW Supabase project
-- 1) Paste/run this entire file in SQL Editor
-- 2) Then import backup JSON with: node scripts/importDbBackup.js

-- AUTO-GENERATED from supabase/sql/schema.sql (JSON introspection)
-- Public base tables + constraints + indexes.
-- Apply in Supabase SQL Editor on a NEW empty project.

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Custom enums used by public tables
DO $$ BEGIN
  CREATE TYPE public.transfer_status AS ENUM ('draft', 'approved', 'dispatched', 'received', 'cancelled');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public."categories" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public."closing_stock_entries" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "session_id" uuid,
  "product_id" uuid,
  "qty" numeric,
  "created_at" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public."combo_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "combo_id" integer,
  "quantity" integer NOT NULL,
  "product_id" uuid
);

CREATE TABLE IF NOT EXISTS public."combo_locations" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "combo_id" integer NOT NULL,
  "location_id" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "assembled_qty" numeric DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS public."combos" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "combo_name" varchar(255) NOT NULL,
  "combo_price" numeric(10,2) NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "standard_price" numeric,
  "promotional_price" numeric,
  "promo_start_date" timestamp,
  "promo_end_date" timestamp,
  "sku" varchar,
  "picture_url" text,
  "product_id" uuid,
  "currency" text,
  "category_id" integer,
  "unit_of_measure_id" integer
);

CREATE TABLE IF NOT EXISTS public."company_settings" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "company_name" text NOT NULL,
  "company_address" text NOT NULL,
  "company_phone" text NOT NULL,
  "company_email" text NOT NULL,
  "company_tpin" text NOT NULL,
  "company_logo" text,
  "created_at" timestamptz DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public."customers" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "name" text,
  "phone" text,
  "address" text,
  "city" text,
  "tpin" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "currency" text,
  "opening_balance" numeric DEFAULT 0 NOT NULL,
  "credit_balance" numeric DEFAULT 0 NOT NULL,
  "country" text
);

CREATE TABLE IF NOT EXISTS public."factory_sold_storage_events" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "storage_id" uuid NOT NULL,
  "event_type" text NOT NULL,
  "quantity" numeric(18,4),
  "before_quantity" numeric(18,4),
  "after_quantity" numeric(18,4),
  "notes" text,
  "metadata" jsonb,
  "created_by" uuid,
  "created_by_user_id" bigint,
  "created_at" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public."factory_sold_storage_items" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "sale_id" integer,
  "sale_item_id" integer,
  "product_id" uuid NOT NULL,
  "location_id" uuid NOT NULL,
  "quantity" numeric(18,4) DEFAULT 0 NOT NULL,
  "quantity_released" numeric(18,4) DEFAULT 0 NOT NULL,
  "status" text DEFAULT 'stored'::text NOT NULL,
  "stored_at" timestamptz DEFAULT now() NOT NULL,
  "expected_release_date" date,
  "released_at" timestamptz,
  "release_reference" text,
  "customer_name" text,
  "customer_phone" text,
  "notes" text,
  "metadata" jsonb,
  "created_by" uuid,
  "created_by_user_id" bigint,
  "updated_by" uuid,
  "updated_by_user_id" bigint,
  "updated_at" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public."incomplete_packages" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "location_id" uuid NOT NULL,
  "combo_id" bigint,
  "item_name" text,
  "quantity" numeric DEFAULT 0 NOT NULL,
  "notes" text,
  "created_at" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public."inventory" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "location" uuid NOT NULL,
  "quantity" integer DEFAULT 0 NOT NULL,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "product_id" uuid
);

CREATE TABLE IF NOT EXISTS public."inventory_adjustments" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "product_id" uuid NOT NULL,
  "location_id" uuid NOT NULL,
  "quantity" numeric NOT NULL,
  "adjustment_type" text NOT NULL,
  "adjusted_at" timestamptz DEFAULT now() NOT NULL,
  "metadata" jsonb
);

CREATE TABLE IF NOT EXISTS public."label_print_jobs" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "status" text DEFAULT 'pending'::text NOT NULL,
  "payload" jsonb NOT NULL,
  "error" text
);

CREATE TABLE IF NOT EXISTS public."layby_payments" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "sale_id" integer NOT NULL,
  "customer_id" uuid NOT NULL,
  "payment_type" text,
  "amount" numeric,
  "currency" text,
  "payment_date" timestamptz,
  "reference" text,
  "notes" text,
  "allocation_batch_uuid" uuid,
  "created_at" timestamptz DEFAULT now(),
  "source_payment_id" uuid,
  "discount_amount" numeric DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS public."laybys" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "sale_id" integer,
  "customer_id" uuid,
  "total_amount" numeric,
  "paid_amount" numeric,
  "status" text,
  "created_at" timestamptz DEFAULT now(),
  "notes" text,
  "updated_at" timestamptz,
  "origin" text DEFAULT 'pos'::text
);

CREATE TABLE IF NOT EXISTS public."ledger_entries" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "direction" text NOT NULL,
  "amount" numeric(14,2) NOT NULL,
  "currency" text DEFAULT 'K'::text NOT NULL,
  "reason" text NOT NULL,
  "reference" text,
  "location_id" uuid,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "created_by" uuid DEFAULT auth.uid(),
  "approved_by" uuid,
  "attachment_url" text
);

CREATE TABLE IF NOT EXISTS public."locations" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "name" text NOT NULL,
  "address" text,
  "city" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."opening_stock_entries" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "session_id" uuid,
  "product_id" uuid,
  "qty" numeric,
  "stocktake_conductor" text
);

CREATE TABLE IF NOT EXISTS public."product_images" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "product_id" uuid,
  "image_url" text NOT NULL,
  "created_at" timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."product_locations" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "product_id" uuid,
  "location_id" uuid
);

CREATE TABLE IF NOT EXISTS public."products" (
  "name" varchar(255) NOT NULL,
  "sku" varchar(255) NOT NULL,
  "sku_type" boolean DEFAULT false NOT NULL,
  "price" numeric(10,2) NOT NULL,
  "promotional_price" numeric(10,2),
  "promo_start_date" timestamp,
  "promo_end_date" timestamp,
  "category_id" integer,
  "unit_of_measure_id" integer,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "cost_price" numeric,
  "standard_price" numeric,
  "currency" text,
  "image_url" text
);

CREATE TABLE IF NOT EXISTS public."quotation_items" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "quotation_id" uuid NOT NULL,
  "product_id" uuid,
  "quote_product_id" uuid,
  "name_override" text,
  "description" text,
  "unit_id" integer,
  "quantity" numeric DEFAULT 1 NOT NULL,
  "unit_price" numeric DEFAULT 0 NOT NULL,
  "sort_order" integer,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."quotation_products" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "quote_sku" text,
  "name" text NOT NULL,
  "price" numeric DEFAULT 0 NOT NULL,
  "unit_id" integer,
  "description" text,
  "active" boolean DEFAULT true NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "image_url" text,
  "qr_code_url" text
);

CREATE TABLE IF NOT EXISTS public."quotation_units" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" text NOT NULL,
  "abbreviation" text,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."quotations" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "quote_number" text,
  "customer_id" uuid,
  "currency" text DEFAULT 'K'::text NOT NULL,
  "discount" numeric DEFAULT 0 NOT NULL,
  "vat_apply" boolean DEFAULT false NOT NULL,
  "vat_inclusive" boolean DEFAULT true NOT NULL,
  "vat_rate" numeric DEFAULT 0.16 NOT NULL,
  "notes" text,
  "status" text DEFAULT 'draft'::text NOT NULL,
  "subtotal" numeric DEFAULT 0 NOT NULL,
  "total" numeric DEFAULT 0 NOT NULL,
  "created_by" uuid,
  "created_at" timestamptz DEFAULT now(),
  "updated_at" timestamptz DEFAULT now(),
  "sale_id" integer,
  "layby_id" uuid
);

CREATE TABLE IF NOT EXISTS public."quote_customers" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "name" text NOT NULL,
  "phone" text,
  "country" text,
  "currency" text DEFAULT 'K'::text NOT NULL,
  "email" text,
  "notes" text,
  "address" text,
  "city" text,
  "tpin" text
);

CREATE TABLE IF NOT EXISTS public."sales" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" integer,
  "total_amount" numeric(10,2) NOT NULL,
  "sale_date" timestamp DEFAULT CURRENT_TIMESTAMP,
  "location_id" uuid,
  "customer_id" uuid,
  "layby_id" uuid,
  "status" text,
  "updated_at" timestamptz,
  "currency" text,
  "discount" numeric,
  "sale_id" text,
  "receipt_number" text,
  "reminder_date" date,
  "vat_apply" boolean DEFAULT false NOT NULL,
  "vat_inclusive" boolean DEFAULT true NOT NULL,
  "vat_rate" numeric DEFAULT 0,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "user_uid" uuid
);

CREATE TABLE IF NOT EXISTS public."sales_items" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sale_id" integer,
  "quantity" integer NOT NULL,
  "unit_price" numeric(10,2) NOT NULL,
  "product_id" uuid,
  "currency" text,
  "display_name" text,
  "color" text
);

CREATE TABLE IF NOT EXISTS public."sales_payments" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "sale_id" integer,
  "payment_type" text,
  "amount" numeric,
  "currency" text,
  "payment_date" timestamptz DEFAULT now(),
  "reference" text,
  "notes" text,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "allocation_batch_uuid" uuid,
  "discount_amount" numeric DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS public."stock_count_checks" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "session_id" uuid NOT NULL,
  "product_id" uuid NOT NULL,
  "location_id" uuid NOT NULL,
  "counted" integer DEFAULT 0 NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "updated_by" uuid
);

CREATE TABLE IF NOT EXISTS public."stock_periods" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "location_id" uuid NOT NULL,
  "opened_at" timestamptz DEFAULT now() NOT NULL,
  "closed_at" timestamptz,
  "status" text DEFAULT 'open'::text NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public."stock_transfer_entries" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "session_id" uuid,
  "product_id" uuid,
  "quantity" numeric NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "updated_at" timestamptz DEFAULT now() NOT NULL,
  "parent_product_id" uuid,
  "variant_label" text,
  "variant_attributes" jsonb
);

CREATE TABLE IF NOT EXISTS public."stock_transfer_sessions" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "from_location" uuid,
  "to_location" uuid,
  "user_id" integer,
  "delivery_number" text,
  "transfer_date" date NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  "notes" text,
  "transfer_datetime" timestamptz,
  "transfer_ts" timestamp,
  "pdf_url" text,
  "status" public.transfer_status,
  "total_qty" numeric,
  "metadata" jsonb,
  "user_uid" uuid
);

CREATE TABLE IF NOT EXISTS public."stocktake_items" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "stocktake_id" uuid NOT NULL,
  "product_id" uuid NOT NULL,
  "qty" numeric DEFAULT 0 NOT NULL,
  "counted_by_name" text,
  "updated_at" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public."stocktakes" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "location_id" uuid NOT NULL,
  "status" text DEFAULT 'open'::text NOT NULL,
  "notes" text,
  "created_by_name" text,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "submitted_at" timestamptz,
  "applied_at" timestamptz,
  "applied_by_name" text,
  "cancelled_at" timestamptz
);

CREATE TABLE IF NOT EXISTS public."unit_of_measure" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "name" varchar(50) NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "abbreviation" varchar
);

CREATE TABLE IF NOT EXISTS public."user_acl" (
  "user_uid" uuid NOT NULL,
  "full_access" boolean DEFAULT true NOT NULL,
  "allowed_locations" uuid[]
);

CREATE TABLE IF NOT EXISTS public."user_activity_log" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "user_uid" uuid,
  "user_email" text,
  "user_name" text,
  "action_type" text NOT NULL,
  "action_label" text NOT NULL,
  "details" text,
  "reference" text,
  "entity_type" text,
  "entity_id" text,
  "route" text,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS public."users" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "email" varchar(255) NOT NULL,
  "password" varchar(255) NOT NULL,
  "role" varchar(50) DEFAULT 'user'::character varying NOT NULL,
  "full_name" varchar(255),
  "avatar_url" varchar(255),
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public."warehouse_delivery_entries" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "session_id" uuid NOT NULL,
  "product_id" uuid,
  "combo_id" integer,
  "kind" text NOT NULL,
  "name" text,
  "sku" text,
  "quantity" numeric DEFAULT 0 NOT NULL,
  "per_set_qty" numeric,
  "max_qty" numeric,
  "created_at" timestamptz DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public."warehouse_delivery_sessions" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "from_location" uuid NOT NULL,
  "to_location" uuid NOT NULL,
  "created_at" timestamptz DEFAULT now() NOT NULL,
  "transfer_datetime" timestamptz,
  "status" text DEFAULT 'pending'::text NOT NULL,
  "total_qty" numeric,
  "created_by_id" integer,
  "created_by_email" text,
  "applied_by" uuid,
  "applied_at" timestamptz,
  "metadata" jsonb
);

DO $$ BEGIN ALTER TABLE public."categories" ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."closing_stock_entries" ADD CONSTRAINT "closing_stock_entries_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."combo_items" ADD CONSTRAINT "combo_items_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."combo_locations" ADD CONSTRAINT "combo_locations_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."combo_locations" ADD CONSTRAINT "unique_combo_location" UNIQUE ("combo_id", "location_id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."combo_locations" ADD CONSTRAINT "uq_combo_locations" UNIQUE ("combo_id", "location_id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."combos" ADD CONSTRAINT "combos_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."company_settings" ADD CONSTRAINT "company_settings_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."customers" ADD CONSTRAINT "customers_opening_balance_nonnegative" CHECK ((opening_balance >= (0)::numeric)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."customers" ADD CONSTRAINT "customers_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."factory_sold_storage_events" ADD CONSTRAINT "factory_sold_storage_events_event_type_check" CHECK ((event_type = ANY (ARRAY['stored'::text, 'released'::text, 'adjustment'::text, 'note'::text]))); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."factory_sold_storage_events" ADD CONSTRAINT "factory_sold_storage_events_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."factory_sold_storage_items" ADD CONSTRAINT "factory_sold_storage_items_check" CHECK ((quantity_released <= quantity)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."factory_sold_storage_items" ADD CONSTRAINT "factory_sold_storage_items_quantity_check" CHECK ((quantity >= (0)::numeric)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."factory_sold_storage_items" ADD CONSTRAINT "factory_sold_storage_items_quantity_released_check" CHECK ((quantity_released >= (0)::numeric)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."factory_sold_storage_items" ADD CONSTRAINT "factory_sold_storage_items_status_check" CHECK ((status = ANY (ARRAY['stored'::text, 'partial'::text, 'released'::text, 'lost'::text, 'cancelled'::text]))); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."factory_sold_storage_items" ADD CONSTRAINT "factory_sold_storage_items_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."incomplete_packages" ADD CONSTRAINT "incomplete_packages_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."inventory" ADD CONSTRAINT "inventory_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."inventory" ADD CONSTRAINT "inventory_product_location_uniq" UNIQUE ("product_id", "location"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."inventory" ADD CONSTRAINT "uq_inventory_product_location" UNIQUE ("product_id", "location"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."inventory_adjustments" ADD CONSTRAINT "inventory_adjustments_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."label_print_jobs" ADD CONSTRAINT "label_print_jobs_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."layby_payments" ADD CONSTRAINT "layby_payments_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."layby_payments" ADD CONSTRAINT "layby_payments_source_payment_id_key" UNIQUE ("source_payment_id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."laybys" ADD CONSTRAINT "laybys_origin_check" CHECK ((origin = ANY (ARRAY['pos'::text, 'quote'::text]))); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."laybys" ADD CONSTRAINT "laybys_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."ledger_entries" ADD CONSTRAINT "ledger_entries_amount_check" CHECK ((amount > (0)::numeric)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."ledger_entries" ADD CONSTRAINT "ledger_entries_direction_check" CHECK ((direction = ANY (ARRAY['credit'::text, 'debit'::text]))); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."ledger_entries" ADD CONSTRAINT "ledger_entries_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."locations" ADD CONSTRAINT "locations_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."opening_stock_entries" ADD CONSTRAINT "opening_stock_entries_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."product_images" ADD CONSTRAINT "product_images_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."product_locations" ADD CONSTRAINT "product_locations_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."product_locations" ADD CONSTRAINT "uq_product_locations" UNIQUE ("product_id", "location_id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."products" ADD CONSTRAINT "products_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."products" ADD CONSTRAINT "products_sku_key" UNIQUE ("sku"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quotation_items" ADD CONSTRAINT "chk_quotation_items_product_present" CHECK (((product_id IS NOT NULL) OR (quote_product_id IS NOT NULL))); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quotation_items" ADD CONSTRAINT "quotation_items_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quotation_products" ADD CONSTRAINT "quotation_products_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quotation_units" ADD CONSTRAINT "quotation_units_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quotations" ADD CONSTRAINT "quotations_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quotations" ADD CONSTRAINT "quotations_quote_number_key" UNIQUE ("quote_number"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quote_customers" ADD CONSTRAINT "quote_customers_name_check" CHECK ((length(btrim(name)) > 0)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quote_customers" ADD CONSTRAINT "quote_customers_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."sales" ADD CONSTRAINT "sales_discount_nonneg" CHECK (((discount IS NULL) OR (discount >= (0)::numeric))); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."sales" ADD CONSTRAINT "sales_status_check" CHECK (((status = ANY (ARRAY['draft'::text, 'confirmed'::text, 'layby'::text, 'completed'::text, 'void'::text, 'refunded'::text])) OR (status IS NULL))); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."sales" ADD CONSTRAINT "sales_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."sales" ADD CONSTRAINT "sales_sale_id_key" UNIQUE ("sale_id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."sales_items" ADD CONSTRAINT "sales_items_product_or_display_name_chk" CHECK (((product_id IS NOT NULL) OR ((display_name IS NOT NULL) AND (btrim(display_name) <> ''::text)))); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."sales_items" ADD CONSTRAINT "sales_items_qty_pos" CHECK ((quantity > 0)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."sales_items" ADD CONSTRAINT "sales_items_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."sales_payments" ADD CONSTRAINT "sales_payments_amount_nonneg" CHECK ((amount >= (0)::numeric)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."sales_payments" ADD CONSTRAINT "sales_payments_payment_type_check" CHECK ((payment_type = ANY (ARRAY['cash'::text, 'bank_transfer'::text, 'mobile_money'::text, 'cheque'::text, 'visa_card'::text, 'credit'::text, 'down_payment'::text, 'goods'::text]))); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."sales_payments" ADD CONSTRAINT "sales_payments_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stock_count_checks" ADD CONSTRAINT "stock_count_checks_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stock_periods" ADD CONSTRAINT "stock_periods_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stock_transfer_entries" ADD CONSTRAINT "stock_transfer_entries_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stock_transfer_sessions" ADD CONSTRAINT "stock_transfer_sessions_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stocktake_items" ADD CONSTRAINT "stocktake_items_qty_check" CHECK ((qty >= (0)::numeric)); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stocktake_items" ADD CONSTRAINT "stocktake_items_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stocktake_items" ADD CONSTRAINT "stocktake_items_unique_product" UNIQUE ("stocktake_id", "product_id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stocktakes" ADD CONSTRAINT "stocktakes_status_check" CHECK ((status = ANY (ARRAY['open'::text, 'submitted'::text, 'applied'::text, 'cancelled'::text]))); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stocktakes" ADD CONSTRAINT "stocktakes_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."unit_of_measure" ADD CONSTRAINT "unit_of_measure_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."unit_of_measure" ADD CONSTRAINT "unit_of_measure_name_key" UNIQUE ("name"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."user_acl" ADD CONSTRAINT "user_acl_pkey" PRIMARY KEY ("user_uid"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."user_activity_log" ADD CONSTRAINT "user_activity_log_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."users" ADD CONSTRAINT "users_email_key" UNIQUE ("email"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."warehouse_delivery_entries" ADD CONSTRAINT "warehouse_delivery_entries_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."warehouse_delivery_sessions" ADD CONSTRAINT "warehouse_delivery_sessions_pkey" PRIMARY KEY ("id"); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN ALTER TABLE public."closing_stock_entries" ADD CONSTRAINT "closing_stock_entries_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES public."products" ("id") ON UPDATE NO ACTION ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."closing_stock_entries" ADD CONSTRAINT "closing_stock_entries_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES public."stock_periods" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."combo_items" ADD CONSTRAINT "combo_items_combo_id_fkey" FOREIGN KEY ("combo_id") REFERENCES public."combos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."combo_items" ADD CONSTRAINT "combo_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES public."products" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."combo_locations" ADD CONSTRAINT "fk_combo" FOREIGN KEY ("combo_id") REFERENCES public."combos" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."combo_locations" ADD CONSTRAINT "fk_location" FOREIGN KEY ("location_id") REFERENCES public."locations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."combos" ADD CONSTRAINT "combos_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES public."categories" ("id") ON UPDATE NO ACTION ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."combos" ADD CONSTRAINT "combos_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES public."products" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."combos" ADD CONSTRAINT "combos_unit_of_measure_id_fkey" FOREIGN KEY ("unit_of_measure_id") REFERENCES public."unit_of_measure" ("id") ON UPDATE NO ACTION ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."factory_sold_storage_events" ADD CONSTRAINT "factory_sold_storage_events_storage_id_fkey" FOREIGN KEY ("storage_id") REFERENCES public."factory_sold_storage_items" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."factory_sold_storage_items" ADD CONSTRAINT "factory_sold_storage_items_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES public."locations" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."factory_sold_storage_items" ADD CONSTRAINT "factory_sold_storage_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES public."products" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."factory_sold_storage_items" ADD CONSTRAINT "factory_sold_storage_items_sale_id_fkey" FOREIGN KEY ("sale_id") REFERENCES public."sales" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."factory_sold_storage_items" ADD CONSTRAINT "factory_sold_storage_items_sale_item_id_fkey" FOREIGN KEY ("sale_item_id") REFERENCES public."sales_items" ("id") ON UPDATE NO ACTION ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."incomplete_packages" ADD CONSTRAINT "incomplete_packages_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES public."locations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."inventory" ADD CONSTRAINT "inventory_location_fkey" FOREIGN KEY ("location") REFERENCES public."locations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."inventory" ADD CONSTRAINT "inventory_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES public."products" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."inventory_adjustments" ADD CONSTRAINT "inventory_adjustments_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES public."locations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."inventory_adjustments" ADD CONSTRAINT "inventory_adjustments_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES public."products" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."laybys" ADD CONSTRAINT "fk_laybys_customer" FOREIGN KEY ("customer_id") REFERENCES public."customers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."laybys" ADD CONSTRAINT "fk_laybys_sale" FOREIGN KEY ("sale_id") REFERENCES public."sales" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."opening_stock_entries" ADD CONSTRAINT "opening_stock_entries_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES public."products" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."product_images" ADD CONSTRAINT "product_images_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES public."products" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."product_locations" ADD CONSTRAINT "product_locations_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES public."locations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."product_locations" ADD CONSTRAINT "product_locations_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES public."products" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."products" ADD CONSTRAINT "products_category_id_fkey" FOREIGN KEY ("category_id") REFERENCES public."categories" ("id") ON UPDATE NO ACTION ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."products" ADD CONSTRAINT "products_unit_of_measure_id_fkey" FOREIGN KEY ("unit_of_measure_id") REFERENCES public."unit_of_measure" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quotation_items" ADD CONSTRAINT "fk_quotation_items_quote" FOREIGN KEY ("quotation_id") REFERENCES public."quotations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quotation_items" ADD CONSTRAINT "quotation_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES public."products" ("id") ON UPDATE NO ACTION ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quotation_items" ADD CONSTRAINT "quotation_items_quotation_id_fkey" FOREIGN KEY ("quotation_id") REFERENCES public."quotations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quotation_items" ADD CONSTRAINT "quotation_items_quote_product_id_fkey" FOREIGN KEY ("quote_product_id") REFERENCES public."quotation_products" ("id") ON UPDATE NO ACTION ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quotation_items" ADD CONSTRAINT "quotation_items_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES public."quotation_units" ("id") ON UPDATE NO ACTION ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quotation_products" ADD CONSTRAINT "quotation_products_unit_id_fkey" FOREIGN KEY ("unit_id") REFERENCES public."quotation_units" ("id") ON UPDATE NO ACTION ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quotations" ADD CONSTRAINT "quotations_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES public."customers" ("id") ON UPDATE NO ACTION ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quotations" ADD CONSTRAINT "quotations_layby_id_fkey" FOREIGN KEY ("layby_id") REFERENCES public."laybys" ("id") ON UPDATE NO ACTION ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."quotations" ADD CONSTRAINT "quotations_sale_id_fkey" FOREIGN KEY ("sale_id") REFERENCES public."sales" ("id") ON UPDATE NO ACTION ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."sales" ADD CONSTRAINT "sales_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES public."customers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."sales" ADD CONSTRAINT "sales_layby_id_fkey" FOREIGN KEY ("layby_id") REFERENCES public."laybys" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."sales" ADD CONSTRAINT "sales_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES public."locations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."sales" ADD CONSTRAINT "sales_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
-- Skipped FK sales_user_uid_fkey: sales -> auth.users
DO $$ BEGIN ALTER TABLE public."sales_items" ADD CONSTRAINT "sales_items_sale_id_fkey" FOREIGN KEY ("sale_id") REFERENCES public."sales" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."sales_payments" ADD CONSTRAINT "fk_sales_payments_sale" FOREIGN KEY ("sale_id") REFERENCES public."sales" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stock_count_checks" ADD CONSTRAINT "stock_count_checks_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES public."locations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stock_count_checks" ADD CONSTRAINT "stock_count_checks_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES public."products" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stock_count_checks" ADD CONSTRAINT "stock_count_checks_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES public."stock_periods" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stock_periods" ADD CONSTRAINT "stock_periods_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES public."locations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stock_transfer_entries" ADD CONSTRAINT "stock_transfer_entries_parent_product_id_fkey" FOREIGN KEY ("parent_product_id") REFERENCES public."products" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stock_transfer_entries" ADD CONSTRAINT "stock_transfer_entries_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES public."products" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stock_transfer_entries" ADD CONSTRAINT "stock_transfer_entries_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES public."stock_transfer_sessions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stock_transfer_sessions" ADD CONSTRAINT "stock_transfer_sessions_from_location_fkey" FOREIGN KEY ("from_location") REFERENCES public."locations" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stock_transfer_sessions" ADD CONSTRAINT "stock_transfer_sessions_to_location_fkey" FOREIGN KEY ("to_location") REFERENCES public."locations" ("id") ON UPDATE NO ACTION ON DELETE RESTRICT; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stock_transfer_sessions" ADD CONSTRAINT "stock_transfer_sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES public."users" ("id") ON UPDATE NO ACTION ON DELETE SET NULL; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
-- Skipped FK stock_transfer_sessions_user_uid_fkey: stock_transfer_sessions -> auth.users
DO $$ BEGIN ALTER TABLE public."stocktake_items" ADD CONSTRAINT "stocktake_items_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES public."products" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stocktake_items" ADD CONSTRAINT "stocktake_items_stocktake_id_fkey" FOREIGN KEY ("stocktake_id") REFERENCES public."stocktakes" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."stocktakes" ADD CONSTRAINT "stocktakes_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES public."locations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."warehouse_delivery_entries" ADD CONSTRAINT "warehouse_delivery_entries_combo_id_fkey" FOREIGN KEY ("combo_id") REFERENCES public."combos" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."warehouse_delivery_entries" ADD CONSTRAINT "warehouse_delivery_entries_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES public."products" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."warehouse_delivery_entries" ADD CONSTRAINT "warehouse_delivery_entries_session_id_fkey" FOREIGN KEY ("session_id") REFERENCES public."warehouse_delivery_sessions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."warehouse_delivery_sessions" ADD CONSTRAINT "warehouse_delivery_sessions_from_location_fkey" FOREIGN KEY ("from_location") REFERENCES public."locations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE public."warehouse_delivery_sessions" ADD CONSTRAINT "warehouse_delivery_sessions_to_location_fkey" FOREIGN KEY ("to_location") REFERENCES public."locations" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION; EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE UNIQUE INDEX IF NOT EXISTS ux_closing_entries_session_product ON public.closing_stock_entries USING btree (session_id, product_id);
CREATE INDEX IF NOT EXISTS idx_combo_items_combo ON public.combo_items USING btree (combo_id);
CREATE INDEX IF NOT EXISTS ix_combo_items_combo_id ON public.combo_items USING btree (combo_id);
CREATE INDEX IF NOT EXISTS idx_combo_locations_combo_location ON public.combo_locations USING btree (combo_id, location_id);
CREATE UNIQUE INDEX IF NOT EXISTS unique_combo_location ON public.combo_locations USING btree (combo_id, location_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_combo_locations ON public.combo_locations USING btree (combo_id, location_id);
CREATE INDEX IF NOT EXISTS combos_category_id_idx ON public.combos USING btree (category_id);
CREATE INDEX IF NOT EXISTS combos_unit_of_measure_id_idx ON public.combos USING btree (unit_of_measure_id);
CREATE INDEX IF NOT EXISTS idx_customers_advance_balance ON public.customers USING btree (credit_balance);
CREATE INDEX IF NOT EXISTS idx_customers_advance_balance_pos ON public.customers USING btree (credit_balance) WHERE (credit_balance > (0)::numeric);
CREATE INDEX IF NOT EXISTS idx_customers_name ON public.customers USING gin (to_tsvector('simple'::regconfig, COALESCE(name, ''::text)));
CREATE INDEX IF NOT EXISTS idx_customers_name_trgm ON public.customers USING btree (name);
CREATE INDEX IF NOT EXISTS idx_customers_phone ON public.customers USING btree (phone);
CREATE INDEX IF NOT EXISTS idx_customers_phone_trgm ON public.customers USING btree (phone);
CREATE INDEX IF NOT EXISTS factory_sold_storage_events_storage_idx ON public.factory_sold_storage_events USING btree (storage_id, created_at DESC);
CREATE INDEX IF NOT EXISTS factory_sold_storage_items_sale_idx ON public.factory_sold_storage_items USING btree (sale_id, sale_item_id);
CREATE INDEX IF NOT EXISTS factory_sold_storage_items_status_idx ON public.factory_sold_storage_items USING btree (status, location_id, stored_at DESC);
CREATE INDEX IF NOT EXISTS idx_incomplete_packages_combo ON public.incomplete_packages USING btree (combo_id);
CREATE INDEX IF NOT EXISTS idx_incomplete_packages_location ON public.incomplete_packages USING btree (location_id);
CREATE INDEX IF NOT EXISTS idx_inventory_location ON public.inventory USING btree (location);
CREATE INDEX IF NOT EXISTS idx_inventory_location_product ON public.inventory USING btree (location, product_id);
CREATE INDEX IF NOT EXISTS idx_inventory_product_location ON public.inventory USING btree (product_id, location);
CREATE UNIQUE INDEX IF NOT EXISTS inventory_product_location_uniq ON public.inventory USING btree (product_id, location);
CREATE UNIQUE INDEX IF NOT EXISTS uq_inventory_product_location ON public.inventory USING btree (product_id, location);
CREATE UNIQUE INDEX IF NOT EXISTS ux_inventory_product_location ON public.inventory USING btree (product_id, location);
CREATE INDEX IF NOT EXISTS idx_inventory_adjustments_product_loc_time ON public.inventory_adjustments USING btree (product_id, location_id, adjusted_at DESC);
CREATE INDEX IF NOT EXISTS ix_inv_adj_location_time ON public.inventory_adjustments USING btree (location_id, adjusted_at);
CREATE INDEX IF NOT EXISTS ix_inv_adj_product_loc_time ON public.inventory_adjustments USING btree (product_id, location_id, adjusted_at);
CREATE INDEX IF NOT EXISTS ix_inventory_adjustments_product_location ON public.inventory_adjustments USING btree (product_id, location_id);
CREATE INDEX IF NOT EXISTS label_print_jobs_status_idx ON public.label_print_jobs USING btree (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_layby_payments_customer_id ON public.layby_payments USING btree (customer_id);
CREATE INDEX IF NOT EXISTS idx_layby_payments_payment_date ON public.layby_payments USING btree (payment_date);
CREATE INDEX IF NOT EXISTS idx_layby_payments_sale_id ON public.layby_payments USING btree (sale_id);
CREATE UNIQUE INDEX IF NOT EXISTS layby_payments_source_payment_id_key ON public.layby_payments USING btree (source_payment_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_layby_payments_dedup ON public.layby_payments USING btree (sale_id, payment_date, amount, reference, notes, payment_type);
CREATE INDEX IF NOT EXISTS idx_laybys_customer ON public.laybys USING btree (customer_id);
CREATE INDEX IF NOT EXISTS idx_laybys_customer_created ON public.laybys USING btree (customer_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_laybys_customer_status ON public.laybys USING btree (customer_id, status);
CREATE INDEX IF NOT EXISTS idx_laybys_sale ON public.laybys USING btree (sale_id);
CREATE INDEX IF NOT EXISTS idx_laybys_status ON public.laybys USING btree (status);
CREATE INDEX IF NOT EXISTS idx_laybys_updated_at ON public.laybys USING btree (updated_at DESC);
CREATE INDEX IF NOT EXISTS ledger_entries_created_at_idx ON public.ledger_entries USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS ledger_entries_currency_idx ON public.ledger_entries USING btree (currency);
CREATE INDEX IF NOT EXISTS ledger_entries_location_idx ON public.ledger_entries USING btree (location_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_opening_entries_session_product ON public.opening_stock_entries USING btree (session_id, product_id);
CREATE INDEX IF NOT EXISTS idx_product_images_product ON public.product_images USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_product_images_product_id ON public.product_images USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_product_locations_location_id ON public.product_locations USING btree (location_id);
CREATE INDEX IF NOT EXISTS idx_product_locations_product_location ON public.product_locations USING btree (product_id, location_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_product_locations ON public.product_locations USING btree (product_id, location_id);
CREATE INDEX IF NOT EXISTS idx_products_category ON public.products USING btree (category_id);
CREATE INDEX IF NOT EXISTS idx_products_created_at_desc ON public.products USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_name_trgm ON public.products USING btree (name);
CREATE INDEX IF NOT EXISTS idx_products_sku ON public.products USING btree (sku);
CREATE INDEX IF NOT EXISTS idx_products_sku_trgm ON public.products USING btree (sku);
CREATE UNIQUE INDEX IF NOT EXISTS products_sku_key ON public.products USING btree (sku);
CREATE INDEX IF NOT EXISTS idx_quotation_items_quotation ON public.quotation_items USING btree (quotation_id);
CREATE INDEX IF NOT EXISTS idx_quotation_items_quote ON public.quotation_items USING btree (quotation_id);
CREATE INDEX IF NOT EXISTS idx_quotation_products_active ON public.quotation_products USING btree (active);
CREATE INDEX IF NOT EXISTS idx_quotation_products_name ON public.quotation_products USING gin (to_tsvector('simple'::regconfig, ((COALESCE(name, ''::text) || ' '::text) || COALESCE(quote_sku, ''::text))));
CREATE INDEX IF NOT EXISTS idx_quotations_created_at_desc ON public.quotations USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_quotations_customer ON public.quotations USING btree (customer_id);
CREATE INDEX IF NOT EXISTS idx_quotations_customer_status_created ON public.quotations USING btree (customer_id, status, created_at);
CREATE INDEX IF NOT EXISTS idx_quotations_layby_id ON public.quotations USING btree (layby_id);
CREATE INDEX IF NOT EXISTS idx_quotations_sale ON public.quotations USING btree (sale_id);
CREATE INDEX IF NOT EXISTS idx_quotations_sale_id ON public.quotations USING btree (sale_id);
CREATE INDEX IF NOT EXISTS idx_quotations_status ON public.quotations USING btree (status);
CREATE UNIQUE INDEX IF NOT EXISTS quotations_quote_number_key ON public.quotations USING btree (quote_number);
CREATE INDEX IF NOT EXISTS quote_customers_name_idx ON public.quote_customers USING btree (lower(name));
CREATE INDEX IF NOT EXISTS quote_customers_phone_idx ON public.quote_customers USING btree (phone);
CREATE INDEX IF NOT EXISTS idx_sales_created_at_desc ON public.sales USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_sales_customer ON public.sales USING btree (customer_id);
CREATE INDEX IF NOT EXISTS idx_sales_customer_date ON public.sales USING btree (customer_id, sale_date DESC);
CREATE INDEX IF NOT EXISTS idx_sales_customer_id ON public.sales USING btree (customer_id);
CREATE INDEX IF NOT EXISTS idx_sales_customer_layby ON public.sales USING btree (customer_id, layby_id);
CREATE INDEX IF NOT EXISTS idx_sales_customer_status ON public.sales USING btree (customer_id, status);
CREATE INDEX IF NOT EXISTS idx_sales_customer_status_date ON public.sales USING btree (customer_id, status, sale_date);
CREATE INDEX IF NOT EXISTS idx_sales_layby ON public.sales USING btree (layby_id);
CREATE INDEX IF NOT EXISTS idx_sales_location_date ON public.sales USING btree (location_id, sale_date);
CREATE INDEX IF NOT EXISTS idx_sales_receipt_number ON public.sales USING btree (receipt_number);
CREATE INDEX IF NOT EXISTS idx_sales_status_date ON public.sales USING btree (status, sale_date DESC);
CREATE INDEX IF NOT EXISTS idx_sales_user_uid ON public.sales USING btree (user_uid);
CREATE INDEX IF NOT EXISTS ix_sales_location_date ON public.sales USING btree (location_id, sale_date);
CREATE UNIQUE INDEX IF NOT EXISTS sales_sale_id_key ON public.sales USING btree (sale_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_sales_receipt ON public.sales USING btree (receipt_number) WHERE ((receipt_number IS NOT NULL) AND (btrim(receipt_number) <> ''::text) AND (receipt_number <> '#-'::text));
CREATE UNIQUE INDEX IF NOT EXISTS ux_sales_receipt_unique_except_fahme ON public.sales USING btree (btrim(receipt_number)) WHERE ((customer_id IS DISTINCT FROM 'd8e756ae-b8ea-4f90-b99a-70c1120f52b9'::uuid) AND (btrim(receipt_number) IS NOT NULL) AND (btrim(receipt_number) <> ''::text));
CREATE UNIQUE INDEX IF NOT EXISTS ux_sales_sale_id ON public.sales USING btree (sale_id) WHERE (sale_id IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_sales_items_product ON public.sales_items USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_sales_items_sale ON public.sales_items USING btree (sale_id);
CREATE INDEX IF NOT EXISTS idx_sales_items_sale2 ON public.sales_items USING btree (sale_id);
CREATE INDEX IF NOT EXISTS idx_sales_items_sale_id ON public.sales_items USING btree (sale_id);
CREATE INDEX IF NOT EXISTS ix_sales_items_sale ON public.sales_items USING btree (sale_id);
CREATE INDEX IF NOT EXISTS idx_sales_payments_alloc_batch ON public.sales_payments USING btree (allocation_batch_uuid);
CREATE INDEX IF NOT EXISTS idx_sales_payments_date ON public.sales_payments USING btree (payment_date);
CREATE INDEX IF NOT EXISTS idx_sales_payments_payment_date ON public.sales_payments USING btree (payment_date);
CREATE INDEX IF NOT EXISTS idx_sales_payments_payment_date_desc ON public.sales_payments USING btree (payment_date DESC);
CREATE INDEX IF NOT EXISTS idx_sales_payments_sale ON public.sales_payments USING btree (sale_id);
CREATE INDEX IF NOT EXISTS idx_sales_payments_sale_date_batch ON public.sales_payments USING btree (sale_id, payment_date, allocation_batch_uuid);
CREATE INDEX IF NOT EXISTS idx_sales_payments_sale_id ON public.sales_payments USING btree (sale_id);
CREATE INDEX IF NOT EXISTS idx_sales_payments_sale_payment_date ON public.sales_payments USING btree (sale_id, payment_date);
CREATE INDEX IF NOT EXISTS idx_sales_payments_sale_type ON public.sales_payments USING btree (sale_id, payment_type);
CREATE UNIQUE INDEX IF NOT EXISTS ux_sales_payments_dedup ON public.sales_payments USING btree (sale_id, payment_date, amount, COALESCE(reference, ''::text), COALESCE(notes, ''::text), lower(payment_type));
CREATE UNIQUE INDEX IF NOT EXISTS stock_count_checks_unique ON public.stock_count_checks USING btree (session_id, product_id);
CREATE INDEX IF NOT EXISTS idx_stock_periods_location_opened_at ON public.stock_periods USING btree (location_id, opened_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_periods_location_status ON public.stock_periods USING btree (location_id, status);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_entries_session ON public.stock_transfer_entries USING btree (session_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_entries_session_created ON public.stock_transfer_entries USING btree (session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_entries_session_created_at ON public.stock_transfer_entries USING btree (session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_transfer_entries_product ON public.stock_transfer_entries USING btree (product_id);
CREATE INDEX IF NOT EXISTS idx_transfer_entries_session ON public.stock_transfer_entries USING btree (session_id);
CREATE INDEX IF NOT EXISTS idx_transfer_entries_session_product ON public.stock_transfer_entries USING btree (session_id, product_id);
CREATE INDEX IF NOT EXISTS ix_transfer_entries_session ON public.stock_transfer_entries USING btree (session_id);
CREATE INDEX IF NOT EXISTS ix_transfer_entries_session_id ON public.stock_transfer_entries USING btree (session_id);
CREATE INDEX IF NOT EXISTS ix_transfer_entries_session_product ON public.stock_transfer_entries USING btree (session_id, product_id);
CREATE INDEX IF NOT EXISTS stock_transfer_entries_product_id_idx ON public.stock_transfer_entries USING btree (product_id);
CREATE INDEX IF NOT EXISTS stock_transfer_entries_session_id_idx ON public.stock_transfer_entries USING btree (session_id);
CREATE INDEX IF NOT EXISTS idx_stock_transfer_sessions_user_uid ON public.stock_transfer_sessions USING btree (user_uid);
CREATE INDEX IF NOT EXISTS idx_transfer_sessions_date ON public.stock_transfer_sessions USING btree (transfer_date);
CREATE INDEX IF NOT EXISTS idx_transfer_sessions_from ON public.stock_transfer_sessions USING btree (from_location);
CREATE INDEX IF NOT EXISTS idx_transfer_sessions_from_to_date ON public.stock_transfer_sessions USING btree (from_location, to_location, transfer_date);
CREATE INDEX IF NOT EXISTS idx_transfer_sessions_from_to_ts ON public.stock_transfer_sessions USING btree (from_location, to_location, transfer_ts DESC);
CREATE INDEX IF NOT EXISTS idx_transfer_sessions_to ON public.stock_transfer_sessions USING btree (to_location);
CREATE INDEX IF NOT EXISTS ix_transfer_sessions_created_at ON public.stock_transfer_sessions USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS ix_transfer_sessions_from_to ON public.stock_transfer_sessions USING btree (from_location, to_location);
CREATE INDEX IF NOT EXISTS ix_transfer_sessions_status ON public.stock_transfer_sessions USING btree (status);
CREATE INDEX IF NOT EXISTS ix_transfer_sessions_to_created ON public.stock_transfer_sessions USING btree (to_location, created_at);
CREATE INDEX IF NOT EXISTS stock_transfer_sessions_metadata_gin_idx ON public.stock_transfer_sessions USING gin (metadata);
CREATE INDEX IF NOT EXISTS stock_transfer_sessions_pdf_url_idx ON public.stock_transfer_sessions USING btree (pdf_url);
CREATE INDEX IF NOT EXISTS stock_transfer_sessions_status_date_idx ON public.stock_transfer_sessions USING btree (status, transfer_date DESC);
CREATE INDEX IF NOT EXISTS stock_transfer_sessions_total_qty_idx ON public.stock_transfer_sessions USING btree (total_qty);
CREATE INDEX IF NOT EXISTS stock_transfer_sessions_transfer_date_idx ON public.stock_transfer_sessions USING btree (transfer_date);
CREATE INDEX IF NOT EXISTS stocktake_items_stocktake_idx ON public.stocktake_items USING btree (stocktake_id);
CREATE UNIQUE INDEX IF NOT EXISTS stocktake_items_unique_product ON public.stocktake_items USING btree (stocktake_id, product_id);
CREATE INDEX IF NOT EXISTS stocktakes_location_created_idx ON public.stocktakes USING btree (location_id, created_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS stocktakes_one_active_per_location ON public.stocktakes USING btree (location_id) WHERE (status = ANY (ARRAY['open'::text, 'submitted'::text]));
CREATE UNIQUE INDEX IF NOT EXISTS unit_of_measure_name_key ON public.unit_of_measure USING btree (name);
CREATE INDEX IF NOT EXISTS idx_user_activity_log_action_type ON public.user_activity_log USING btree (action_type);
CREATE INDEX IF NOT EXISTS idx_user_activity_log_created_at ON public.user_activity_log USING btree (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_user_activity_log_user_uid ON public.user_activity_log USING btree (user_uid);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_key ON public.users USING btree (email);
CREATE INDEX IF NOT EXISTS idx_warehouse_delivery_entries_session_id ON public.warehouse_delivery_entries USING btree (session_id);
CREATE INDEX IF NOT EXISTS idx_warehouse_delivery_sessions_status ON public.warehouse_delivery_sessions USING btree (status);




-- ========== supabase/sql/migrations/20260710_stocktake_flow_v3.sql ==========

-- ============================================================================
-- Stocktake Flow v3
-- Multi-user counting events + period open/close + variance support
-- Does NOT modify existing inventory quantities on migrate.
-- ============================================================================

BEGIN;

-- Old v2 single-cart tables (if present)
DROP TABLE IF EXISTS public.stocktake_items CASCADE;
DROP TABLE IF EXISTS public.stocktakes CASCADE;
DROP TABLE IF EXISTS public.stocktake_user_entries CASCADE;
DROP TABLE IF EXISTS public.stocktake_user_sessions CASCADE;

-- Per-location: initial stocktake completed once forever
CREATE TABLE IF NOT EXISTS public.stocktake_location_state (
  location_id uuid PRIMARY KEY REFERENCES public.locations(id) ON DELETE CASCADE,
  initial_completed boolean NOT NULL DEFAULT false,
  initial_completed_at timestamptz NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Counting event (multiple allowed per location)
CREATE TABLE IF NOT EXISTS public.stocktake_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  location_id uuid NOT NULL REFERENCES public.locations(id),
  status text NOT NULL DEFAULT 'counting'
    CHECK (status IN ('counting', 'submitted', 'cancelled')),
  counting_enabled boolean NOT NULL DEFAULT false,
  is_initial boolean NOT NULL DEFAULT false,
  notes text NULL,
  created_by_email text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  submitted_at timestamptz NULL,
  submitted_by_email text NULL,
  closed_period_id uuid NULL REFERENCES public.stock_periods(id),
  opened_period_id uuid NULL REFERENCES public.stock_periods(id)
);

CREATE INDEX IF NOT EXISTS stocktake_events_location_idx
  ON public.stocktake_events (location_id, created_at DESC);
CREATE INDEX IF NOT EXISTS stocktake_events_status_idx
  ON public.stocktake_events (location_id, status);

-- Cumulative count per user per product per event
CREATE TABLE IF NOT EXISTS public.stocktake_counts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES public.stocktake_events(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES public.products(id),
  user_email text NOT NULL,
  qty numeric NOT NULL DEFAULT 0 CHECK (qty >= 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT stocktake_counts_unique UNIQUE (event_id, product_id, user_email)
);

CREATE INDEX IF NOT EXISTS stocktake_counts_event_idx
  ON public.stocktake_counts (event_id);

-- Each popup add (audit trail)
CREATE TABLE IF NOT EXISTS public.stocktake_count_log (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES public.stocktake_events(id) ON DELETE CASCADE,
  product_id uuid NOT NULL REFERENCES public.products(id),
  user_email text NOT NULL,
  qty_added numeric NOT NULL,
  qty_after numeric NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS stocktake_count_log_event_idx
  ON public.stocktake_count_log (event_id, created_at DESC);

-- Set scans (for variance PDF set reconstruction); cart still stores components
-- combos.id is integer (serial), not uuid
DROP TABLE IF EXISTS public.stocktake_set_scans CASCADE;
CREATE TABLE IF NOT EXISTS public.stocktake_set_scans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES public.stocktake_events(id) ON DELETE CASCADE,
  combo_id integer NOT NULL REFERENCES public.combos(id),
  user_email text NOT NULL,
  set_qty numeric NOT NULL DEFAULT 0 CHECK (set_qty >= 0),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT stocktake_set_scans_unique UNIQUE (event_id, combo_id, user_email)
);

-- Green/red counting gate audit
CREATE TABLE IF NOT EXISTS public.stocktake_gate_audit (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id uuid NOT NULL REFERENCES public.stocktake_events(id) ON DELETE CASCADE,
  location_id uuid NOT NULL REFERENCES public.locations(id),
  enabled boolean NOT NULL,
  changed_by_email text NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Period date columns for variance reports
ALTER TABLE public.stock_periods
  ADD COLUMN IF NOT EXISTS begin_period_date timestamptz,
  ADD COLUMN IF NOT EXISTS end_period_date timestamptz,
  ADD COLUMN IF NOT EXISTS variance_pdf_ready boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS source_event_id uuid NULL;

UPDATE public.stock_periods
  SET begin_period_date = COALESCE(begin_period_date, opened_at)
  WHERE begin_period_date IS NULL;

COMMENT ON TABLE public.stocktake_events IS
  'Multi-user stocktake counting event. Inventory/periods update only on submit.';
COMMENT ON TABLE public.stocktake_counts IS
  'Per-user cumulative product counts within an event.';

ALTER TABLE public.stocktake_location_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stocktake_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stocktake_counts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stocktake_count_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stocktake_set_scans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stocktake_gate_audit ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  CREATE POLICY stocktake_location_state_all ON public.stocktake_location_state FOR ALL TO authenticated USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY stocktake_events_all ON public.stocktake_events FOR ALL TO authenticated USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY stocktake_counts_all ON public.stocktake_counts FOR ALL TO authenticated USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY stocktake_count_log_all ON public.stocktake_count_log FOR ALL TO authenticated USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY stocktake_set_scans_all ON public.stocktake_set_scans FOR ALL TO authenticated USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  CREATE POLICY stocktake_gate_audit_all ON public.stocktake_gate_audit FOR ALL TO authenticated USING (true) WITH CHECK (true);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

COMMIT;




-- ========== supabase/sql/migrations/20260711_warehouse_deliveries_workflow.sql ==========

-- Warehouse Deliveries workflow overhaul
-- Apply manually in Supabase SQL editor (or via migration runner).
-- Extends warehouse_delivery_sessions / warehouse_delivery_entries with
-- delivery numbers, idempotency, audit fields, atomic submit/accept RPCs, and RLS.

BEGIN;

-- ---------------------------------------------------------------------------
-- 1) Session columns
-- ---------------------------------------------------------------------------
ALTER TABLE public.warehouse_delivery_sessions
  ADD COLUMN IF NOT EXISTS delivery_number text,
  ADD COLUMN IF NOT EXISTS idempotency_key text,
  ADD COLUMN IF NOT EXISTS submitted_at timestamptz,
  ADD COLUMN IF NOT EXISTS accepted_by uuid,
  ADD COLUMN IF NOT EXISTS accepted_at timestamptz,
  ADD COLUMN IF NOT EXISTS completed_at timestamptz,
  ADD COLUMN IF NOT EXISTS pdf_url text,
  ADD COLUMN IF NOT EXISTS sync_status text DEFAULT 'synced',
  ADD COLUMN IF NOT EXISTS last_edited_by uuid,
  ADD COLUMN IF NOT EXISTS last_edited_at timestamptz;

-- Backfill delivery_number for existing rows (stable, sortable)
UPDATE public.warehouse_delivery_sessions
SET delivery_number = 'WD-' || to_char(created_at AT TIME ZONE 'Africa/Lusaka', 'YYYYMMDD')
  || '-' || upper(substr(replace(id::text, '-', ''), 1, 8))
WHERE delivery_number IS NULL;

-- Backfill submitted_at from transfer_datetime / created_at
UPDATE public.warehouse_delivery_sessions
SET submitted_at = COALESCE(submitted_at, transfer_datetime, created_at)
WHERE status IN ('pending', 'submitted', 'accepted', 'completed');

-- Normalize legacy accepted → completed (inventory already moved)
UPDATE public.warehouse_delivery_sessions
SET
  status = 'completed',
  accepted_at = COALESCE(accepted_at, applied_at),
  accepted_by = COALESCE(accepted_by, applied_by),
  completed_at = COALESCE(completed_at, applied_at)
WHERE lower(status) = 'accepted';

CREATE UNIQUE INDEX IF NOT EXISTS warehouse_delivery_sessions_idempotency_key_uidx
  ON public.warehouse_delivery_sessions (idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS warehouse_delivery_sessions_delivery_number_uidx
  ON public.warehouse_delivery_sessions (delivery_number)
  WHERE delivery_number IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_warehouse_delivery_sessions_to_status
  ON public.warehouse_delivery_sessions (to_location, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_warehouse_delivery_sessions_delivery_number
  ON public.warehouse_delivery_sessions (delivery_number DESC);

-- ---------------------------------------------------------------------------
-- 2) Entry columns (original vs working quantity)
-- ---------------------------------------------------------------------------
ALTER TABLE public.warehouse_delivery_entries
  ADD COLUMN IF NOT EXISTS original_quantity numeric,
  ADD COLUMN IF NOT EXISTS edited_quantity numeric,
  ADD COLUMN IF NOT EXISTS dest_stock_before numeric,
  ADD COLUMN IF NOT EXISTS expected_dest_stock numeric,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

UPDATE public.warehouse_delivery_entries
SET
  original_quantity = COALESCE(original_quantity, quantity),
  edited_quantity = COALESCE(edited_quantity, quantity)
WHERE original_quantity IS NULL OR edited_quantity IS NULL;

-- ---------------------------------------------------------------------------
-- 3) Audit / event log
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.warehouse_delivery_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL REFERENCES public.warehouse_delivery_sessions(id) ON DELETE CASCADE,
  event_type text NOT NULL,
  actor_id text,
  actor_email text,
  detail jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_warehouse_delivery_events_session
  ON public.warehouse_delivery_events (session_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- 4) Delivery number helper
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.next_warehouse_delivery_number()
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
  day_key text := to_char((now() AT TIME ZONE 'Africa/Lusaka'), 'YYYYMMDD');
  seq int;
BEGIN
  SELECT COALESCE(MAX(
    NULLIF(regexp_replace(delivery_number, '^WD-' || day_key || '-', ''), '')::int
  ), 0) + 1
  INTO seq
  FROM public.warehouse_delivery_sessions
  WHERE delivery_number ~ ('^WD-' || day_key || '-[0-9]+$');

  RETURN 'WD-' || day_key || '-' || lpad(seq::text, 4, '0');
END;
$$;

-- ---------------------------------------------------------------------------
-- 5) Atomic submit (header + items, idempotent)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.submit_warehouse_delivery(
  p_idempotency_key text,
  p_from_location uuid,
  p_to_location uuid,
  p_created_by_id int,
  p_created_by_email text,
  p_items jsonb,
  p_captured_at timestamptz DEFAULT now()
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_existing public.warehouse_delivery_sessions%ROWTYPE;
  v_session public.warehouse_delivery_sessions%ROWTYPE;
  v_item jsonb;
  v_total numeric := 0;
  v_qty numeric;
  v_kind text;
  v_from constant uuid := '39ffaa82-8aee-4a33-8de8-06584cbaffcf'::uuid;
  v_to constant uuid := '454a092c-5b12-441e-b99d-216f6fa72198'::uuid;
BEGIN
  IF p_idempotency_key IS NULL OR length(trim(p_idempotency_key)) < 8 THEN
    RAISE EXCEPTION 'idempotency_key required';
  END IF;
  IF p_from_location IS DISTINCT FROM v_from OR p_to_location IS DISTINCT FROM v_to THEN
    RAISE EXCEPTION 'Transfer locations are locked to Factory → Kitwe';
  END IF;
  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'At least one delivery item is required';
  END IF;

  SELECT * INTO v_existing
  FROM public.warehouse_delivery_sessions
  WHERE idempotency_key = p_idempotency_key
  LIMIT 1;

  IF FOUND THEN
    RETURN jsonb_build_object(
      'ok', true,
      'duplicate', true,
      'session', to_jsonb(v_existing)
    );
  END IF;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_kind := coalesce(v_item->>'kind', 'product');
    IF v_kind = 'set-parent' THEN
      CONTINUE;
    END IF;
    v_qty := coalesce((v_item->>'quantity')::numeric, 0);
    IF v_qty <= 0 THEN
      RAISE EXCEPTION 'Invalid quantity for item %', coalesce(v_item->>'name', v_item->>'sku', '?');
    END IF;
    v_total := v_total + v_qty;
  END LOOP;

  IF v_total <= 0 THEN
    RAISE EXCEPTION 'Delivery total quantity must be > 0';
  END IF;

  INSERT INTO public.warehouse_delivery_sessions (
    from_location,
    to_location,
    created_at,
    transfer_datetime,
    submitted_at,
    status,
    total_qty,
    created_by_id,
    created_by_email,
    delivery_number,
    idempotency_key,
    sync_status,
    metadata
  ) VALUES (
    v_from,
    v_to,
    coalesce(p_captured_at, now()),
    coalesce(p_captured_at, now()),
    coalesce(p_captured_at, now()),
    'pending',
    v_total,
    p_created_by_id,
    p_created_by_email,
    public.next_warehouse_delivery_number(),
    p_idempotency_key,
    'synced',
    jsonb_build_object(
      'created_by_id', p_created_by_id,
      'created_by_email', p_created_by_email,
      'source', 'warehouse_transfers_app'
    )
  )
  RETURNING * INTO v_session;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_qty := coalesce((v_item->>'quantity')::numeric, 0);
    IF v_qty <= 0 AND coalesce(v_item->>'kind', 'product') <> 'set-parent' THEN
      CONTINUE;
    END IF;
    INSERT INTO public.warehouse_delivery_entries (
      session_id,
      product_id,
      combo_id,
      kind,
      name,
      sku,
      quantity,
      original_quantity,
      edited_quantity,
      per_set_qty,
      max_qty
    ) VALUES (
      v_session.id,
      NULLIF(v_item->>'product_id', '')::uuid,
      NULLIF(v_item->>'combo_id', '')::int,
      coalesce(v_item->>'kind', 'product'),
      coalesce(v_item->>'name', ''),
      NULLIF(v_item->>'sku', ''),
      v_qty,
      v_qty,
      v_qty,
      NULLIF(v_item->>'per_set_qty', '')::numeric,
      NULLIF(v_item->>'max_qty', '')::numeric
    );
  END LOOP;

  INSERT INTO public.warehouse_delivery_events (session_id, event_type, actor_id, actor_email, detail)
  VALUES (
    v_session.id,
    'submitted',
    coalesce(p_created_by_id::text, ''),
    p_created_by_email,
    jsonb_build_object('total_qty', v_total, 'idempotency_key', p_idempotency_key)
  );

  RETURN jsonb_build_object(
    'ok', true,
    'duplicate', false,
    'session', to_jsonb(v_session)
  );
EXCEPTION
  WHEN unique_violation THEN
    SELECT * INTO v_existing
    FROM public.warehouse_delivery_sessions
    WHERE idempotency_key = p_idempotency_key
    LIMIT 1;
    RETURN jsonb_build_object(
      'ok', true,
      'duplicate', true,
      'session', to_jsonb(v_existing)
    );
END;
$$;

REVOKE ALL ON FUNCTION public.submit_warehouse_delivery(text, uuid, uuid, int, text, jsonb, timestamptz) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.submit_warehouse_delivery(text, uuid, uuid, int, text, jsonb, timestamptz) TO anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 6) Atomic accept + inventory move
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.accept_warehouse_delivery(
  p_session_id uuid,
  p_accepted_by uuid,
  p_accepted_by_email text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session public.warehouse_delivery_sessions%ROWTYPE;
  v_from constant uuid := '39ffaa82-8aee-4a33-8de8-06584cbaffcf'::uuid;
  v_to constant uuid := '454a092c-5b12-441e-b99d-216f6fa72198'::uuid;
  v_hassan constant uuid := '6b992ac8-8e39-4f31-a323-2271a974da8c'::uuid;
  r record;
  v_qty numeric;
  v_src numeric;
  v_dst numeric;
  v_src_id uuid;
  v_dst_id uuid;
  v_now timestamptz := now();
BEGIN
  IF p_session_id IS NULL THEN
    RAISE EXCEPTION 'session id required';
  END IF;
  IF p_accepted_by IS DISTINCT FROM v_hassan THEN
    RAISE EXCEPTION 'Only the authorised receiver can accept warehouse deliveries';
  END IF;

  SELECT * INTO v_session
  FROM public.warehouse_delivery_sessions
  WHERE id = p_session_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Delivery not found';
  END IF;

  IF v_session.from_location IS DISTINCT FROM v_from
     OR v_session.to_location IS DISTINCT FROM v_to THEN
    RAISE EXCEPTION 'Delivery locations do not match Factory → Kitwe';
  END IF;

  IF lower(v_session.status) IN ('completed', 'accepted') THEN
    RETURN jsonb_build_object(
      'ok', true,
      'already_completed', true,
      'session', to_jsonb(v_session)
    );
  END IF;

  IF lower(v_session.status) NOT IN ('pending', 'submitted') THEN
    RAISE EXCEPTION 'Delivery status % cannot be accepted', v_session.status;
  END IF;

  FOR r IN
    SELECT *
    FROM public.warehouse_delivery_entries
    WHERE session_id = p_session_id
      AND coalesce(kind, 'product') <> 'set-parent'
      AND coalesce(edited_quantity, quantity, 0) > 0
      AND product_id IS NOT NULL
  LOOP
    v_qty := coalesce(r.edited_quantity, r.quantity, 0);

    SELECT id, quantity INTO v_src_id, v_src
    FROM public.inventory
    WHERE product_id = r.product_id AND location = v_from
    FOR UPDATE;
    v_src := coalesce(v_src, 0);
    IF v_src < v_qty THEN
      RAISE EXCEPTION 'Insufficient Factory stock for % (have %, need %)',
        coalesce(r.name, r.sku, r.product_id::text), v_src, v_qty;
    END IF;

    SELECT id, quantity INTO v_dst_id, v_dst
    FROM public.inventory
    WHERE product_id = r.product_id AND location = v_to
    FOR UPDATE;
    v_dst := coalesce(v_dst, 0);

    UPDATE public.warehouse_delivery_entries
    SET
      quantity = v_qty,
      edited_quantity = v_qty,
      original_quantity = coalesce(original_quantity, quantity, v_qty),
      dest_stock_before = v_dst,
      expected_dest_stock = v_dst + v_qty,
      updated_at = v_now
    WHERE id = r.id;

    IF v_src_id IS NULL THEN
      RAISE EXCEPTION 'Missing Factory inventory row for %', coalesce(r.name, r.product_id::text);
    END IF;
    UPDATE public.inventory
    SET quantity = v_src - v_qty, updated_at = v_now
    WHERE id = v_src_id;

    IF v_dst_id IS NULL THEN
      INSERT INTO public.inventory (product_id, location, quantity, updated_at)
      VALUES (r.product_id, v_to, v_qty, v_now);
    ELSE
      UPDATE public.inventory
      SET quantity = v_dst + v_qty, updated_at = v_now
      WHERE id = v_dst_id;
    END IF;
  END LOOP;

  UPDATE public.warehouse_delivery_sessions
  SET
    status = 'completed',
    applied_by = p_accepted_by,
    applied_at = v_now,
    accepted_by = p_accepted_by,
    accepted_at = v_now,
    completed_at = v_now,
    metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
      'accepted_by', p_accepted_by,
      'accepted_at', v_now,
      'accepted_by_email', p_accepted_by_email
    )
  WHERE id = p_session_id
  RETURNING * INTO v_session;

  INSERT INTO public.warehouse_delivery_events (session_id, event_type, actor_id, actor_email, detail)
  VALUES (
    p_session_id,
    'completed',
    p_accepted_by::text,
    p_accepted_by_email,
    jsonb_build_object('status', 'completed')
  );

  RETURN jsonb_build_object(
    'ok', true,
    'already_completed', false,
    'session', to_jsonb(v_session)
  );
END;
$$;

REVOKE ALL ON FUNCTION public.accept_warehouse_delivery(uuid, uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.accept_warehouse_delivery(uuid, uuid, text) TO anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 7) Admin edit pending delivery quantities (no inventory move)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.update_warehouse_delivery_items(
  p_session_id uuid,
  p_items jsonb,
  p_edited_by uuid,
  p_edited_by_email text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_session public.warehouse_delivery_sessions%ROWTYPE;
  v_item jsonb;
  v_entry_id uuid;
  v_qty numeric;
  v_total numeric := 0;
  v_now timestamptz := now();
BEGIN
  SELECT * INTO v_session
  FROM public.warehouse_delivery_sessions
  WHERE id = p_session_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Delivery not found';
  END IF;

  IF lower(v_session.status) IN ('completed', 'accepted') THEN
    RAISE EXCEPTION 'Completed deliveries cannot be edited here';
  END IF;
  IF lower(v_session.status) NOT IN ('pending', 'submitted') THEN
    RAISE EXCEPTION 'Delivery status % cannot be edited', v_session.status;
  END IF;

  FOR v_item IN SELECT * FROM jsonb_array_elements(coalesce(p_items, '[]'::jsonb))
  LOOP
    v_entry_id := NULLIF(v_item->>'id', '')::uuid;
    v_qty := coalesce((v_item->>'quantity')::numeric, 0);
    IF v_entry_id IS NULL THEN
      CONTINUE;
    END IF;
    IF v_qty < 0 THEN
      RAISE EXCEPTION 'Quantities cannot be negative';
    END IF;

    UPDATE public.warehouse_delivery_entries
    SET
      quantity = v_qty,
      edited_quantity = v_qty,
      original_quantity = coalesce(original_quantity, quantity),
      updated_at = v_now
    WHERE id = v_entry_id
      AND session_id = p_session_id;
  END LOOP;

  SELECT coalesce(sum(coalesce(edited_quantity, quantity, 0)), 0)
  INTO v_total
  FROM public.warehouse_delivery_entries
  WHERE session_id = p_session_id
    AND coalesce(kind, 'product') <> 'set-parent';

  UPDATE public.warehouse_delivery_sessions
  SET
    total_qty = v_total,
    last_edited_by = p_edited_by,
    last_edited_at = v_now,
    metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object(
      'last_edited_by', p_edited_by,
      'last_edited_at', v_now,
      'last_edited_by_email', p_edited_by_email
    )
  WHERE id = p_session_id
  RETURNING * INTO v_session;

  INSERT INTO public.warehouse_delivery_events (session_id, event_type, actor_id, actor_email, detail)
  VALUES (
    p_session_id,
    'edited',
    coalesce(p_edited_by::text, ''),
    p_edited_by_email,
    jsonb_build_object('total_qty', v_total, 'items', p_items)
  );

  RETURN jsonb_build_object('ok', true, 'session', to_jsonb(v_session));
END;
$$;

REVOKE ALL ON FUNCTION public.update_warehouse_delivery_items(uuid, jsonb, uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.update_warehouse_delivery_items(uuid, jsonb, uuid, text) TO authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 8) RLS — permissive enough for existing anon-key Android + authenticated web
--    Inventory remains protected; accept/submit run as SECURITY DEFINER.
-- ---------------------------------------------------------------------------
ALTER TABLE public.warehouse_delivery_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.warehouse_delivery_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.warehouse_delivery_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS wd_sessions_select ON public.warehouse_delivery_sessions;
DROP POLICY IF EXISTS wd_sessions_insert ON public.warehouse_delivery_sessions;
DROP POLICY IF EXISTS wd_sessions_update ON public.warehouse_delivery_sessions;
DROP POLICY IF EXISTS wd_entries_select ON public.warehouse_delivery_entries;
DROP POLICY IF EXISTS wd_entries_insert ON public.warehouse_delivery_entries;
DROP POLICY IF EXISTS wd_entries_update ON public.warehouse_delivery_entries;
DROP POLICY IF EXISTS wd_entries_delete ON public.warehouse_delivery_entries;
DROP POLICY IF EXISTS wd_events_select ON public.warehouse_delivery_events;
DROP POLICY IF EXISTS wd_events_insert ON public.warehouse_delivery_events;

CREATE POLICY wd_sessions_select ON public.warehouse_delivery_sessions
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY wd_sessions_insert ON public.warehouse_delivery_sessions
  FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY wd_sessions_update ON public.warehouse_delivery_sessions
  FOR UPDATE TO anon, authenticated
  USING (lower(status) IN ('pending', 'submitted'))
  WITH CHECK (true);

CREATE POLICY wd_entries_select ON public.warehouse_delivery_entries
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY wd_entries_insert ON public.warehouse_delivery_entries
  FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY wd_entries_update ON public.warehouse_delivery_entries
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY wd_entries_delete ON public.warehouse_delivery_entries
  FOR DELETE TO authenticated USING (true);

CREATE POLICY wd_events_select ON public.warehouse_delivery_events
  FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY wd_events_insert ON public.warehouse_delivery_events
  FOR INSERT TO anon, authenticated WITH CHECK (true);

COMMIT;




-- ========== supabase/sql/migrations/20260711_warehouse_delivery_created_by_name.sql ==========

-- Additive: store sender display name on warehouse deliveries.
-- Safe to run after 20260711_warehouse_deliveries_workflow.sql

BEGIN;

ALTER TABLE public.warehouse_delivery_sessions
  ADD COLUMN IF NOT EXISTS created_by_name text;

-- Prefer users.full_name as the WhatsApp / UI "Sent By" name.
UPDATE public.warehouse_delivery_sessions s
SET created_by_name = u.full_name
FROM public.users u
WHERE s.created_by_id = u.id
  AND (s.created_by_name IS NULL OR btrim(s.created_by_name) = '')
  AND u.full_name IS NOT NULL
  AND btrim(u.full_name) <> '';

-- Replace submit RPC so it accepts and resolves created_by_name.
DROP FUNCTION IF EXISTS public.submit_warehouse_delivery(text, uuid, uuid, int, text, jsonb, timestamptz);

CREATE OR REPLACE FUNCTION public.submit_warehouse_delivery(
  p_idempotency_key text,
  p_from_location uuid,
  p_to_location uuid,
  p_created_by_id int,
  p_created_by_email text,
  p_items jsonb,
  p_captured_at timestamptz DEFAULT now(),
  p_created_by_name text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_existing public.warehouse_delivery_sessions%ROWTYPE;
  v_session public.warehouse_delivery_sessions%ROWTYPE;
  v_item jsonb;
  v_total numeric := 0;
  v_qty numeric;
  v_kind text;
  v_name text;
  v_from constant uuid := '39ffaa82-8aee-4a33-8de8-06584cbaffcf'::uuid;
  v_to constant uuid := '454a092c-5b12-441e-b99d-216f6fa72198'::uuid;
BEGIN
  IF p_idempotency_key IS NULL OR length(trim(p_idempotency_key)) < 8 THEN
    RAISE EXCEPTION 'idempotency_key required';
  END IF;
  IF p_from_location IS DISTINCT FROM v_from OR p_to_location IS DISTINCT FROM v_to THEN
    RAISE EXCEPTION 'Transfer locations are locked to Factory → Kitwe';
  END IF;
  IF p_items IS NULL OR jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'At least one delivery item is required';
  END IF;

  SELECT * INTO v_existing
  FROM public.warehouse_delivery_sessions
  WHERE idempotency_key = p_idempotency_key
  LIMIT 1;

  IF FOUND THEN
    RETURN jsonb_build_object(
      'ok', true,
      'duplicate', true,
      'session', to_jsonb(v_existing)
    );
  END IF;

  -- Resolve display name: explicit arg → users.full_name → email
  v_name := nullif(btrim(coalesce(p_created_by_name, '')), '');
  IF v_name IS NULL AND p_created_by_id IS NOT NULL THEN
    SELECT nullif(btrim(full_name), '') INTO v_name
    FROM public.users
    WHERE id = p_created_by_id;
  END IF;
  IF v_name IS NULL THEN
    v_name := nullif(btrim(coalesce(p_created_by_email, '')), '');
  END IF;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_kind := coalesce(v_item->>'kind', 'product');
    IF v_kind = 'set-parent' THEN
      CONTINUE;
    END IF;
    v_qty := coalesce((v_item->>'quantity')::numeric, 0);
    IF v_qty <= 0 THEN
      RAISE EXCEPTION 'Invalid quantity for item %', coalesce(v_item->>'name', v_item->>'sku', '?');
    END IF;
    v_total := v_total + v_qty;
  END LOOP;

  IF v_total <= 0 THEN
    RAISE EXCEPTION 'Delivery total quantity must be > 0';
  END IF;

  INSERT INTO public.warehouse_delivery_sessions (
    from_location,
    to_location,
    created_at,
    transfer_datetime,
    submitted_at,
    status,
    total_qty,
    created_by_id,
    created_by_email,
    created_by_name,
    delivery_number,
    idempotency_key,
    sync_status,
    metadata
  ) VALUES (
    v_from,
    v_to,
    coalesce(p_captured_at, now()),
    coalesce(p_captured_at, now()),
    coalesce(p_captured_at, now()),
    'pending',
    v_total,
    p_created_by_id,
    p_created_by_email,
    v_name,
    public.next_warehouse_delivery_number(),
    p_idempotency_key,
    'synced',
    jsonb_build_object(
      'created_by_id', p_created_by_id,
      'created_by_email', p_created_by_email,
      'created_by_name', v_name,
      'source', 'warehouse_transfers_app'
    )
  )
  RETURNING * INTO v_session;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_qty := coalesce((v_item->>'quantity')::numeric, 0);
    IF v_qty <= 0 AND coalesce(v_item->>'kind', 'product') <> 'set-parent' THEN
      CONTINUE;
    END IF;
    INSERT INTO public.warehouse_delivery_entries (
      session_id,
      product_id,
      combo_id,
      kind,
      name,
      sku,
      quantity,
      original_quantity,
      edited_quantity,
      per_set_qty,
      max_qty
    ) VALUES (
      v_session.id,
      NULLIF(v_item->>'product_id', '')::uuid,
      NULLIF(v_item->>'combo_id', '')::int,
      coalesce(v_item->>'kind', 'product'),
      coalesce(v_item->>'name', ''),
      NULLIF(v_item->>'sku', ''),
      v_qty,
      v_qty,
      v_qty,
      NULLIF(v_item->>'per_set_qty', '')::numeric,
      NULLIF(v_item->>'max_qty', '')::numeric
    );
  END LOOP;

  INSERT INTO public.warehouse_delivery_events (session_id, event_type, actor_id, actor_email, detail)
  VALUES (
    v_session.id,
    'submitted',
    coalesce(p_created_by_id::text, ''),
    p_created_by_email,
    jsonb_build_object(
      'total_qty', v_total,
      'idempotency_key', p_idempotency_key,
      'created_by_name', v_name
    )
  );

  RETURN jsonb_build_object(
    'ok', true,
    'duplicate', false,
    'session', to_jsonb(v_session)
  );
EXCEPTION
  WHEN unique_violation THEN
    SELECT * INTO v_existing
    FROM public.warehouse_delivery_sessions
    WHERE idempotency_key = p_idempotency_key
    LIMIT 1;
    RETURN jsonb_build_object(
      'ok', true,
      'duplicate', true,
      'session', to_jsonb(v_existing)
    );
END;
$$;

REVOKE ALL ON FUNCTION public.submit_warehouse_delivery(text, uuid, uuid, int, text, jsonb, timestamptz, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.submit_warehouse_delivery(text, uuid, uuid, int, text, jsonb, timestamptz, text) TO anon, authenticated, service_role;

COMMIT;


